<?php
// title, description, keywords
class JConfig {
	var $offline = '0';
	var $editor = 'tinymce';
	var $list_limit = '5';
	var $helpurl = 'http://help.joomla.org';
	var $debug = '0';
	var $debug_lang = '0';
	var $sef = '0';
	var $sef_rewrite = '0';
	var $sef_suffix = '0';
	var $feed_limit = '10';
	var $feed_email = 'author';
	var $secret = 'zlKan4JUtSAEUNz8';
	var $gzip = '0';
	var $error_reporting = '-1';
	var $xmlrpc_server = '0';
	var $log_path = 'logs';
	var $tmp_path = 'tmp';
	var $live_site = '';
	var $force_ssl = '0';
	var $offset = '0';
	var $caching = '0';
	var $cachetime = '15';
	var $cache_handler = 'file';
	var $memcache_settings = array();
	var $ftp_enable = '0';
	var $ftp_host = '127.0.0.1';
	var $ftp_port = '21';
	var $ftp_user = '';
	var $ftp_pass = '';
	var $ftp_root = '';
	var $dbtype = 'mysql';
	var $host = 'localhost';
	var $user = 'wt1000333_5';
	var $db = 'wt1000333_5';
	var $dbprefix = 'jos_';
	var $mailer = 'mail';
	var $mailfrom = 'bris@bris.ru';
	var $fromname = 'BRIS. Шины и диски.';
	var $sendmail = '/usr/sbin/sendmail';
	var $smtpauth = '0';
	var $smtpsecure = 'none';
	var $smtpport = '25';
	var $smtpuser = '';
	var $smtppass = '';
	var $smtphost = 'localhost';
	var $MetaAuthor = '1';
	var $MetaTitle = '1';
	var $lifetime = '50';
	var $session_handler = 'database';
	var $password = 'AkmeiTsL';
	var $sitename = 'BRIS. Шины и диски.';
	var $MetaDesc = '';
	var $MetaKeys = 'Bris auto';
	var $offline_message = 'Сайт сейчас закрыт на техническое обслуживание. Пожалуйста зайдите позже.';
}
?>